# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c8688204df7d09fe56959ca4749990996bced01494791db5dbcf3d880f4bcfb3ca5295c404dbb0915445fcfc53836fb2205ae36925cb77ebe674a5187518eb5

test:
  secret_key_base: 8a44534bbd1fbefc7f342c9678893a31df4cd857c146330304462f10a114cb57a785f46d5273c6f581557b8adf9ebfa96e8ea026580650dcb007579db043c2de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
